"use client";
import {useMemo,useState} from "react";
import {ArrowRight,Check,ChevronDown,Instagram,MapPin,Minus,Phone,Plus,ShoppingBag,Truck,Utensils,Whatsapp, X} from "lucide-react";

type Product={id:number;name:string;category:string;price:number;description:string;image:string;popular?:boolean};
const products:Product[]=[
{id:1,name:"Classic Small Chops",category:"Small Chops",price:4500,description:"Crispy spring rolls, samosa, puff-puff and tasty party bites.",image:"https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=900&q=85",popular:true},
{id:2,name:"Loaded Small Chops Tray",category:"Small Chops",price:8500,description:"A generous mixed tray for sharing, meetings and celebrations.",image:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=85"},
{id:3,name:"KAF Chicken Burger",category:"Burger",price:4500,description:"Juicy chicken patty, fresh vegetables and house sauce in a soft bun.",image:"https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85",popular:true},
{id:4,name:"KAF Beef Burger",category:"Burger",price:5000,description:"Savory beef patty, cheese, crunchy greens and signature sauce.",image:"https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85"},
{id:5,name:"Chicken Shawarma",category:"Shawarma",price:4500,description:"Seasoned chicken, fresh veggies and creamy sauce wrapped to order.",image:"https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=900&q=85",popular:true},
{id:6,name:"Beef Shawarma",category:"Shawarma",price:5000,description:"Tender beef, crisp vegetables and KAF sauce in a warm wrap.",image:"https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=900&q=85"},
{id:7,name:"Chicken Sandwich",category:"Sandwich",price:4000,description:"Toasted sandwich layered with chicken, vegetables and house dressing.",image:"https://images.unsplash.com/photo-1521390188846-e2a7d42d0c2c?auto=format&fit=crop&w=900&q=85"},
{id:8,name:"Club Sandwich",category:"Sandwich",price:5500,description:"A filling multi-layer sandwich made for serious hunger.",image:"https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=900&q=85"}
];
const cats=["All","Small Chops","Burger","Shawarma","Sandwich"];
const money=(n:number)=>`₦${n.toLocaleString()}`;
const WA="2349053551681";
export default function Home(){
 const [cat,setCat]=useState("All"); const [cart,setCart]=useState<Record<number,number>>({}); const [open,setOpen]=useState(false);
 const shown=useMemo(()=>cat==="All"?products:products.filter(p=>p.category===cat),[cat]);
 const items=products.filter(p=>cart[p.id]); const count=items.reduce((a,p)=>a+(cart[p.id]||0),0); const total=items.reduce((a,p)=>a+p.price*(cart[p.id]||0),0);
 const add=(id:number)=>setCart(c=>({...c,[id]:(c[id]||0)+1})); const sub=(id:number)=>setCart(c=>{const n=(c[id]||0)-1; const x={...c}; if(n<=0)delete x[id];else x[id]=n;return x});
 const checkout=()=>{if(!items.length)return;const lines=items.map(p=>`• ${p.name} x${cart[p.id]} — ${money(p.price*cart[p.id])}`).join("\n");const msg=`Hello KAF Eatables 👋\n\nI'd like to place an order:\n${lines}\n\nTotal: ${money(total)}\n\nPlease confirm availability, delivery/pickup options and next steps.`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,"_blank")};
 return <main className="min-h-screen grain">
  <header className="sticky top-0 z-40 border-b border-black/5 bg-[#fff9ef]/90 backdrop-blur-md"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 md:px-6"><a href="#top" className="text-2xl font-black tracking-tight">KAF<span className="text-[#ef6c2f]">.</span></a><nav className="hidden gap-7 text-sm font-semibold md:flex"><a href="#menu">Menu</a><a href="#catering">Catering</a><a href="#about">About</a><a href="#contact">Contact</a></nav><button onClick={()=>setOpen(true)} className="relative flex items-center gap-2 rounded-full bg-[#24170f] px-4 py-2 text-sm font-bold text-white"><ShoppingBag size={17}/> Cart {count>0&&<span className="rounded-full bg-[#ffbf45] px-2 py-0.5 text-xs text-[#24170f]">{count}</span>}</button></div></header>
  <section id="top" className="mx-auto grid max-w-6xl items-center gap-10 px-4 pb-16 pt-12 md:grid-cols-2 md:px-6 md:pb-24 md:pt-20"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-[#294d38] px-4 py-2 text-xs font-bold uppercase tracking-wider text-white"><span className="h-2 w-2 rounded-full bg-[#ffbf45]"/> Freshly made • Lagos</div><h1 className="max-w-xl text-5xl font-black leading-[.98] tracking-[-.04em] md:text-7xl">Good food.<br/><span className="text-[#ef6c2f]">Good mood.</span><br/>Just WhatsApp.</h1><p className="mt-6 max-w-lg text-lg leading-7 text-black/65">Small chops, burgers, shawarma and sandwiches made for cravings, hangouts and celebrations.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#menu" className="flex items-center gap-2 rounded-full bg-[#ef6c2f] px-6 py-3.5 font-bold text-white shadow-soft">Explore menu <ArrowRight size={18}/></a><button onClick={()=>window.open(`https://wa.me/${WA}?text=${encodeURIComponent("Hello KAF Eatables 👋 I want to make an enquiry.")}`,"_blank")} className="flex items-center gap-2 rounded-full border border-black/10 bg-white px-6 py-3.5 font-bold"><span>WhatsApp us</span></button></div><div className="mt-7 flex flex-wrap gap-5 text-sm font-semibold text-black/60"><span className="flex items-center gap-2"><Truck size={17}/> Delivery available</span><span className="flex items-center gap-2"><Utensils size={17}/> Event catering</span></div></div><div className="relative"><div className="absolute -left-5 top-10 hidden h-24 w-24 rounded-full bg-[#ffbf45] md:block"/><div className="overflow-hidden rounded-[2rem] shadow-soft"><img src="https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=90" className="h-[470px] w-full object-cover" alt="KAF Eatables food spread"/></div><div className="absolute -bottom-5 -left-4 rounded-2xl bg-white p-4 shadow-soft md:left-5"><p className="text-xs font-bold uppercase tracking-wider text-black/50">Order direct</p><p className="mt-1 font-black">No app. No hassle. 💬</p></div></div></section>
  <section id="menu" className="bg-white py-16 md:py-20"><div className="mx-auto max-w-6xl px-4 md:px-6"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="font-bold uppercase tracking-[.2em] text-[#ef6c2f]">The menu</p><h2 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">Pick your craving.</h2></div><div className="flex flex-wrap gap-2">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`rounded-full px-4 py-2 text-sm font-bold transition ${cat===c?"bg-[#24170f] text-white":"bg-[#fff5e7] text-[#24170f] hover:bg-[#ffe8c8]"}`}>{c}</button>)}</div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{shown.map(p=><article key={p.id} className="group overflow-hidden rounded-3xl border border-black/5 bg-[#fff9ef] shadow-sm"><div className="relative aspect-square overflow-hidden"><img src={p.image} alt={p.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>{p.popular&&<span className="absolute left-3 top-3 rounded-full bg-[#ffbf45] px-3 py-1 text-xs font-black">POPULAR</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-black/45">{p.category}</p><h3 className="mt-1 font-black">{p.name}</h3></div><span className="font-black text-[#ef6c2f]">{money(p.price)}</span></div><p className="mt-2 text-sm leading-5 text-black/55">{p.description}</p><button onClick={()=>add(p.id)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#24170f] py-3 font-bold text-white">Add to order <Plus size={17}/></button></div></article>)}</div></div></section>
  <section id="catering" className="bg-[#294d38] py-16 text-white md:py-20"><div className="mx-auto grid max-w-6xl gap-10 px-4 md:grid-cols-2 md:px-6 md:items-center"><div><p className="font-bold uppercase tracking-[.2em] text-[#ffbf45]">Big orders welcome</p><h2 className="mt-3 text-4xl font-black tracking-tight md:text-5xl">Planning an event? Feed the whole vibe.</h2><p className="mt-5 max-w-xl text-white/75">We cater for birthdays, office events, parties, intimate gatherings and celebrations. KAF can also travel for your event.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/10 p-4"><b>Event catering</b><p className="mt-1 text-sm text-white/65">Custom quantities & trays.</p></div><div className="rounded-2xl bg-white/10 p-4"><b>We can travel</b><p className="mt-1 text-sm text-white/65">Tell us your location & date.</p></div></div><button onClick={()=>window.open(`https://wa.me/${WA}?text=${encodeURIComponent("Hello KAF Eatables 👋 I need catering for an event.\n\nEvent date:\nLocation:\nNumber of guests:\nWhat I'd like:\n")}`,"_blank")} className="mt-7 rounded-full bg-[#ffbf45] px-6 py-3.5 font-black text-[#24170f]">Plan my event on WhatsApp →</button></div><div className="overflow-hidden rounded-[2rem]"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1100&q=85" className="h-[390px] w-full object-cover" alt="Catering spread"/></div></div></section>
  <section id="about" className="py-16 md:py-20"><div className="mx-auto max-w-6xl px-4 md:px-6"><div className="grid gap-8 rounded-[2rem] bg-[#fff] p-7 shadow-soft md:grid-cols-3 md:p-10"><div><p className="text-sm font-bold uppercase tracking-wider text-[#ef6c2f]">Why KAF?</p><h2 className="mt-2 text-3xl font-black">Made for the moment.</h2></div><div className="text-sm leading-6 text-black/60">Whether it is a quick lunch, a weekend craving or a full event, KAF Eatables keeps ordering simple: choose your food, send your order and chat with us on WhatsApp.</div><div className="flex flex-col gap-3 text-sm font-bold"><span className="flex items-center gap-2"><Check size={17} className="text-[#ef6c2f]"/> Freshly prepared</span><span className="flex items-center gap-2"><Check size={17} className="text-[#ef6c2f]"/> Event-ready catering</span><span className="flex items-center gap-2"><Check size={17} className="text-[#ef6c2f]"/> Direct WhatsApp ordering</span></div></div></div></section>
  <footer id="contact" className="bg-[#24170f] py-12 text-white"><div className="mx-auto grid max-w-6xl gap-8 px-4 md:grid-cols-3 md:px-6"><div><div className="text-2xl font-black">KAF<span className="text-[#ef6c2f]">.</span></div><p className="mt-3 max-w-sm text-sm leading-6 text-white/60">Small chops • Burger • Shawarma • Sandwich. We cater for events and are available to travel.</p></div><div><p className="font-bold">Call / WhatsApp</p><a className="mt-3 block text-white/70" href="tel:+2349053551681">0905 355 1681</a><a className="mt-1 block text-white/70" href="tel:+2348125261879">0812 526 1879</a></div><div><p className="font-bold">Order direct</p><button onClick={checkout} className="mt-3 rounded-full bg-[#ef6c2f] px-5 py-3 font-bold">Send order to WhatsApp</button><a className="mt-4 flex items-center gap-2 text-sm text-white/60" href="https://www.instagram.com/p/Cq7YzkZqvhF/?img_index=1" target="_blank"><Instagram size={16}/> Instagram</a></div></div><div className="mx-auto mt-10 max-w-6xl border-t border-white/10 px-4 pt-5 text-xs text-white/35 md:px-6">© {new Date().getFullYear()} KAF Eatables. Built for fast, friendly ordering.</div></footer>
  {open&&<div className="fixed inset-0 z-50 bg-black/40 p-4" onClick={()=>setOpen(false)}><aside className="ml-auto flex h-full w-full max-w-md flex-col rounded-3xl bg-[#fff9ef] shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b border-black/5 p-5"><div><h2 className="text-xl font-black">Your order</h2><p className="text-sm text-black/50">Review before sending to WhatsApp</p></div><button onClick={()=>setOpen(false)} className="rounded-full bg-black/5 p-2"><X size={18}/></button></div><div className="flex-1 overflow-auto p-5">{items.length===0?<div className="py-20 text-center"><ShoppingBag className="mx-auto opacity-30" size={42}/><p className="mt-3 font-bold">Your cart is empty</p><p className="mt-1 text-sm text-black/50">Add something delicious from the menu.</p></div>:<div className="space-y-4">{items.map(p=><div key={p.id} className="flex gap-3 rounded-2xl bg-white p-3"><img src={p.image} className="h-16 w-16 rounded-xl object-cover" alt=""/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="truncate font-bold">{p.name}</p><p className="font-black">{money(p.price*cart[p.id])}</p></div><p className="text-sm text-black/50">{money(p.price)} each</p><div className="mt-2 inline-flex items-center gap-3 rounded-full bg-black/5 px-2 py-1"><button onClick={()=>sub(p.id)}><Minus size={14}/></button><span className="min-w-4 text-center text-sm font-bold">{cart[p.id]}</span><button onClick={()=>add(p.id)}><Plus size={14}/></button></div></div></div>)}</div>}</div>{items.length>0&&<div className="border-t border-black/5 p-5"><div className="mb-4 flex justify-between"><span className="font-semibold text-black/60">Estimated total</span><span className="text-xl font-black">{money(total)}</span></div><button onClick={checkout} className="w-full rounded-2xl bg-[#25D366] py-4 font-black text-[#082b15]">Send order on WhatsApp →</button><p className="mt-2 text-center text-xs text-black/45">KAF will confirm availability, delivery and final total in chat.</p></div>}</aside></div>}
  <button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-30 flex items-center gap-2 rounded-full bg-[#25D366] px-5 py-4 font-black text-[#082b15] shadow-2xl md:hidden"><ShoppingBag size={18}/> {count?`${count} item${count>1?'s':''}`:'Order'} </button>
 </main>
}
